
apiVersion: v1
kind: Service
metadata:
  name: acme-api
  labels:
    {{- include "acme.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "acme.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
