
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  rules:
  - host: acme.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: acme
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: acme
            port:
              number: 3000
{{- end }}
